name: build-push-image

on:
  push:
    branches:
      - main
    workflow_dispatch:
jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Log into registry
        #run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login ${{ secrets.DOCKER_REGISTRY_URL }} -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        run: docker login docker.pkg.github.com -u RaiyanYahyaDev -p ${{ secrets.GITHUB_TOKEN }}
      - name: Build the Docker container image2
        run: | 
             docker build -t docker.pkg.github.com/raiyanyahyadev/builpipe/test:latest .
      - name: docker images2
        run: |
             docker images
      - name: Push the image to Github Packages Repository2
        run: |
             docker login docker.pkg.github.com -u publisher -p "${{ secrets.GITHUB_TOKEN }}"
             docker push docker.pkg.github.com/raiyanyahyadev/builpipe/test:latest
